--CREAR ESQUEMA RAW
DROP SCHEMA IF EXISTS raw CASCADE;
CREATE SCHEMA IF NOT EXISTS raw; 


--QUITAR TABLA SI NO EXISTE
DROP TABLE IF EXISTS raw.borrador;

-- CREAR TABLA CON ESPECIFICACIONES
CREATE TABLE raw.borrador (
	id BIGINT,
    lat NUMERIC,
    long NUMERIC,
    observed_on_x DATE,
    time_zone TEXT,
    elevation NUMERIC,
    time TIMESTAMP,
    temperature_2m NUMERIC,
    relativehumidity_2m NUMERIC,
    dewpoint_2m NUMERIC,
    apparent_temperature NUMERIC,
    surface_pressure NUMERIC,
    precipitation NUMERIC,
    rain NUMERIC,
    snowfall NUMERIC,
    cloudcover NUMERIC,
    cloudcover_low NUMERIC,
    cloudcover_mid NUMERIC,
    cloudcover_high NUMERIC,
    shortwave_radiation NUMERIC,
    direct_radiation NUMERIC,
    diffuse_radiation NUMERIC,
    windspeed_10m NUMERIC,
    windspeed_100m NUMERIC,
    winddirection_10m NUMERIC,
    winddirection_100m NUMERIC,
    windgusts_10m NUMERIC,
    et0_fao_evapotranspiration_hourly NUMERIC,
    weathercode_hourly TEXT,
    vapor_pressure_deficit NUMERIC,
    soil_temperature_0_to_7cm NUMERIC,
    soil_temperature_7_to_28cm NUMERIC,
    soil_temperature_28_to_100cm NUMERIC,
    soil_moisture_0_to_7cm NUMERIC,
    soil_moisture_7_to_28cm NUMERIC,
    soil_moisture_28_to_100cm NUMERIC,
    weathercode_daily TEXT,
    temperature_2m_max NUMERIC,
    temperature_2m_min NUMERIC,
    apparent_temperature_max NUMERIC,
    apparent_temperature_min NUMERIC,
    precipitation_sum NUMERIC,
    rain_sum NUMERIC,
    snowfall_sum NUMERIC,
    precipitation_hours NUMERIC,
    sunrise TEXT,
    sunset TEXT,
    windspeed_10m_max NUMERIC,
    windgusts_10m_max NUMERIC,
    winddirection_10m_dominant NUMERIC,
    shortwave_radiation_sum NUMERIC,
    et0_fao_evapotranspiration_daily NUMERIC,
	observed_on_y DATE, 
    local_time_observed_at TIMESTAMPTZ, 
    latitude NUMERIC(10, 8), 
    longitude NUMERIC(11, 8), 
    positional_accuracy BIGINT, 
    public_positional_accuracy BIGINT, 
    image_url TEXT, 
    license TEXT, 
    geoprivacy TEXT, 
    taxon_geoprivacy TEXT, 
    scientific_name TEXT, 
    common_name TEXT, 
    taxon_id BIGINT 
	
);


--COPIAR LOS DATOS (HACERLO EN PSQL, SOLO HACER COPY PASTE)
COPY raw.borrador (
    id,
    lat,
    long,
    observed_on_x,
    time_zone,
    elevation,
    time,
    temperature_2m,
    relativehumidity_2m,
    dewpoint_2m,
    apparent_temperature,
    surface_pressure,
    precipitation,
    rain,
    snowfall,
    cloudcover,
    cloudcover_low,
    cloudcover_mid,
    cloudcover_high,
    shortwave_radiation,
    direct_radiation,
    diffuse_radiation,
    windspeed_10m,
    windspeed_100m,
    winddirection_10m,
    winddirection_100m,
    windgusts_10m,
    et0_fao_evapotranspiration_hourly,
    weathercode_hourly,
    vapor_pressure_deficit,
    soil_temperature_0_to_7cm,
    soil_temperature_7_to_28cm,
    soil_temperature_28_to_100cm,
    soil_moisture_0_to_7cm,
    soil_moisture_7_to_28cm,
    soil_moisture_28_to_100cm,
    weathercode_daily,
    temperature_2m_max,
    temperature_2m_min,
    apparent_temperature_max,
    apparent_temperature_min,
    precipitation_sum,
    rain_sum,
    snowfall_sum,
    precipitation_hours,
    sunrise,
    sunset,
    windspeed_10m_max,
    windgusts_10m_max,
    winddirection_10m_dominant,
    shortwave_radiation_sum,
    et0_fao_evapotranspiration_daily,
    observed_on_y,
    local_time_observed_at,
    latitude,
    longitude,
    positional_accuracy,
    public_positional_accuracy,
    image_url,
    license,
    geoprivacy,
    taxon_geoprivacy,
    scientific_name,
    common_name,
    taxon_id
    --AQUI PON LA DIRECCION DONDE TENGAS EL UTF8 (COPY PASTEAR ESTE PASO EN PSQL)
) FROM 'C:/Users/andre/OneDrive/Desktop/archive/bonus/data_50000_mammaliaUTF8.csv' WITH (FORMAT CSV, HEADER true, DELIMITER ',');


